name: Clone
on:
  #Run every 12 hours
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: andrewthetechie/gha-clone-releases@v1.7.0
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          src_repo: stars-one/XnApp-PC
          dst_repo: stars-one/XnApp-PC-Release
          copy_assets: true
